export const PREFIX_MULTIPLIERS = {
	Q: 1e30,
	R: 1e27,
	Y: 1e24,
	Z: 1e21,
	E: 1e18,
	P: 1e15,
	T: 1e12,
	G: 1e9,
	M: 1e6,
	k: 1e3,
	h: 1e2,
	da: 1e1,
	"": 1,
	d: 1e-1,
	c: 1e-2,
	m: 1e-3,
	µ: 1e-6,
	n: 1e-9,
	p: 1e-12,
	f: 1e-15,
	a: 1e-18,
	z: 1e-21,
	y: 1e-24,
	r: 1e-27,
	q: 1e-30,
};
export const PREFIX_NAMES = {
	Q: "quetta",
	R: "ronna",
	Y: "yotta",
	Z: "zetta",
	E: "exa",
	P: "peta",
	T: "tera",
	G: "giga",
	M: "mega",
	k: "kilo",
	h: "hecto",
	da: "deca",
	"": "",
	d: "deci",
	c: "centi",
	m: "milli",
	µ: "micro",
	n: "nano",
	p: "pico",
	f: "femto",
	a: "atto",
	z: "zepto",
	y: "yocto",
	r: "ronto",
	q: "quecto",
};
export const UNIT_DEFINITIONS = {
	s: {
		name: "second",
		dim: { Time: 1 },
		factor: 1,
		allowPrefix: true,
		category: "time",
		aliases: ["sec"],
	},
	m: {
		name: "meter",
		dim: { Length: 1 },
		factor: 1,
		allowPrefix: true,
		category: "geometry",
		aliases: ["meter"],
	},
	g: {
		name: "gram",
		dim: { Mass: 1 },
		factor: 1,
		allowPrefix: true,
		category: "mass",
	},
	A: {
		name: "ampere",
		dim: { ElectricCurrent: 1 },
		factor: 1,
		allowPrefix: true,
		category: "electrical",
		aliases: ["amp"],
	},
	K: {
		name: "kelvin",
		dim: { Temperature: 1 },
		factor: 1,
		allowPrefix: true,
		category: "temperature",
		aliases: ["kelvin", "degK"],
	},
	mol: {
		name: "mole",
		dim: { AmountOfSubstance: 1 },
		factor: 1,
		allowPrefix: true,
		category: "chemistry",
	},
	day: {
		name: "day",
		plural: "days",
		dim: { Time: 1 },
		factor: 86400,
		allowPrefix: false,
		category: "time",
		aliases: ["day"],
	},
	cd: {
		name: "candela",
		dim: { LuminousIntensity: 1 },
		factor: 1,
		allowPrefix: true,
		category: "photometry",
	},

	Hz: {
		name: "hertz",
		dim: { Time: -1 },
		factor: 1,
		allowPrefix: true,
		category: "time",
		invariantPlural: true,
	},
	deg: {
		name: "degree",
		plural: "degrees",
		dim: { PlaneAngle: 1 },
		factor: Math.PI / 180,
		allowPrefix: false,
		category: "geometry",
		hint: "Type deg (no ° symbol).",
	},
	arcmin: {
		name: "arcminute",
		dim: { PlaneAngle: 1 },
		factor: Math.PI / 10800,
		allowPrefix: false,
		category: "geometry",
		aliases: ["arcminute"],
		hint: "Type arcmin (no ′ character).",
	},
	arcsec: {
		name: "arcsecond",
		dim: { PlaneAngle: 1 },
		factor: Math.PI / 648000,
		allowPrefix: false,
		category: "geometry",
		aliases: ["arcsecond"],
		hint: "Type arcsec (no ″ character).",
	},
	rad: {
		name: "radian",
		dim: { PlaneAngle: 1 },
		factor: 1,
		allowPrefix: false,
		category: "geometry",
	},
	sr: {
		name: "steradian",
		dim: { SolidAngle: 1 },
		factor: 1,
		allowPrefix: false,
		category: "geometry",
	},
	N: {
		name: "newton",
		dim: { Mass: 1, Length: 1, Time: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "mechanical",
	},
	Pa: {
		name: "pascal",
		dim: { Mass: 1, Length: -1, Time: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "mechanical",
	},
	J: {
		name: "joule",
		dim: { Mass: 1, Length: 2, Time: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "mechanical",
	},
	W: {
		name: "watt",
		dim: { Mass: 1, Length: 2, Time: -3 },
		factor: 1e3,
		allowPrefix: true,
		category: "mechanical",
	},
	C: {
		name: "coulomb",
		dim: { ElectricCurrent: 1, Time: 1 },
		factor: 1,
		allowPrefix: true,
		category: "electrical",
		aliases: ["coul"],
	},
	V: {
		name: "volt",
		dim: { Mass: 1, Length: 2, Time: -3, ElectricCurrent: -1 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	Wb: {
		name: "weber",
		dim: { Mass: 1, Length: 2, Time: -2, ElectricCurrent: -1 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	T: {
		name: "tesla",
		dim: { Mass: 1, Time: -2, ElectricCurrent: -1 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	F: {
		name: "farad",
		dim: { Mass: -1, Length: -2, Time: 4, ElectricCurrent: 2 },
		factor: 1 / 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	ohm: {
		name: "ohm",
		dim: { Mass: 1, Length: 2, Time: -3, ElectricCurrent: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	S: {
		name: "siemens",
		dim: { Mass: -1, Length: -2, Time: 3, ElectricCurrent: 2 },
		factor: 1 / 1e3,
		allowPrefix: true,
		category: "electrical",
		invariantPlural: true,
	},
	H: {
		name: "henry",
		dim: { Mass: 1, Length: 2, Time: -2, ElectricCurrent: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	degC: {
		name: "degree Celsius",
		plural: "degrees Celsius",
		dim: { Temperature: 1 },
		factor: 1,
		offset: 273.15,
		allowPrefix: false,
		category: "temperature",
		hint: "Type degC (no ° symbol).",
	},
	lm: {
		name: "lumen",
		dim: { LuminousIntensity: 1, SolidAngle: 1 },
		factor: 1,
		allowPrefix: true,
		category: "photometry",
	},
	lx: {
		name: "lux",
		dim: { LuminousIntensity: 1, Length: -2 },
		factor: 1,
		allowPrefix: true,
		category: "photometry",
		invariantPlural: true,
	},
	Bq: {
		name: "becquerel",
		dim: { Time: -1 },
		factor: 1,
		allowPrefix: true,
		category: "radioactivity",
	},
	Gy: {
		name: "gray",
		plural: "grays",
		dim: { Length: 2, Time: -2 },
		factor: 1,
		allowPrefix: true,
		category: "radiation",
	},
	Sv: {
		name: "sievert",
		dim: { Length: 2, Time: -2 },
		factor: 1,
		allowPrefix: true,
		category: "radiation",
	},
	kat: {
		name: "katal",
		dim: { AmountOfSubstance: 1, Time: -1 },
		factor: 1,
		allowPrefix: true,
		category: "chemistry",
	},

	h: {
		name: "hour",
		dim: { Time: 1 },
		factor: 3600,
		allowPrefix: false,
		category: "time",
		aliases: ["hr"],
	},
	min: {
		name: "minute",
		dim: { Time: 1 },
		factor: 60,
		allowPrefix: false,
		category: "time",
	},
	L: {
		name: "litre",
		dim: { Length: 3 },
		factor: 1e-3,
		allowPrefix: true,
		category: "geometry",
		aliases: ["l", "liter", "litre"],
	},
	ha: {
		name: "hectare",
		dim: { Length: 2 },
		factor: 1e4,
		allowPrefix: false,
		category: "geometry",
		aliases: ["hectare"],
	},
	t: {
		name: "tonne",
		dim: { Mass: 1 },
		factor: 1e6,
		allowPrefix: false,
		aliases: ["tonne", "ton"],
		category: "mass",
	},
	eV: {
		name: "electronvolt",
		dim: { Mass: 1, Length: 2, Time: -2 },
		factor: 1.602176634e-19 * 1e3,
		allowPrefix: true,
		category: "mechanical",
		aliases: ["electronvolt", "ev"],
	},
	Da: {
		name: "dalton",
		dim: { Mass: 1 },
		factor: 1.6605390666e-24,
		allowPrefix: true,
		category: "mass",
		aliases: ["u", "amu", "dalton"],
	},
	bar: {
		name: "bar",
		dim: { Mass: 1, Length: -1, Time: -2 },
		factor: 1e5 * 1e3,
		allowPrefix: false,
		category: "mechanical",
		aliases: ["b"],
	},
	atm: {
		name: "standard atmosphere",
		dim: { Mass: 1, Length: -1, Time: -2 },
		factor: 101325 * 1e3,
		allowPrefix: false,
		category: "mechanical",
		aliases: ["atmosphere"],
	},
	Torr: {
		name: "torr",
		dim: { Mass: 1, Length: -1, Time: -2 },
		factor: (101325 / 760) * 1e3,
		allowPrefix: false,
		category: "mechanical",
		aliases: ["torr", "mmHg"],
	},
	B: {
		name: "bel",
		dim: { LogLevelBel: 1 },
		factor: 1,
		allowPrefix: true,
		category: "logarithmicBel",
		aliases: ["bel"],
		hint: "Use B for bel; decibel is dB.",
	},
	Np: {
		name: "neper",
		dim: { LogLevelNeper: 1 },
		factor: 1,
		allowPrefix: false,
		category: "logarithmicNeper",
		aliases: ["neper"],
		hint: "Use Np (capital N, lower p).",
	},
};
export const UNIT_ALIASES = Object.entries(UNIT_DEFINITIONS).flatMap(([key, def]) =>
	(def.aliases || []).map((alias) => [alias, key]),
);
export const ALL_UNIT_SYMBOLS = [
	...Object.keys(UNIT_DEFINITIONS),
	...UNIT_ALIASES.map(([alias]) => alias),
].sort((a, b) => b.length - a.length);
export const BASE_UNITS = Object.keys(UNIT_DEFINITIONS).sort((a, b) => b.length - a.length);
export const PREFIXES = Object.keys(PREFIX_MULTIPLIERS);
