// Metric prefix scale factors. The empty-string entry represents "no prefix" so
// prefix lookup code can use one table for prefixed and unprefixed units.
export const PREFIX_MULTIPLIERS = {
	Q: 1e30,
	R: 1e27,
	Y: 1e24,
	Z: 1e21,
	E: 1e18,
	P: 1e15,
	T: 1e12,
	G: 1e9,
	M: 1e6,
	k: 1e3,
	h: 1e2,
	da: 1e1,
	"": 1,
	d: 1e-1,
	c: 1e-2,
	m: 1e-3,
	µ: 1e-6,
	n: 1e-9,
	p: 1e-12,
	f: 1e-15,
	a: 1e-18,
	z: 1e-21,
	y: 1e-24,
	r: 1e-27,
	q: 1e-30,
};
// Human-readable prefix names used in plain-English display and tooltip text.
export const PREFIX_NAMES = {
	Q: "quetta",
	R: "ronna",
	Y: "yotta",
	Z: "zetta",
	E: "exa",
	P: "peta",
	T: "tera",
	G: "giga",
	M: "mega",
	k: "kilo",
	h: "hecto",
	da: "deca",
	"": "",
	d: "deci",
	c: "centi",
	m: "milli",
	µ: "micro",
	n: "nano",
	p: "pico",
	f: "femto",
	a: "atto",
	z: "zepto",
	y: "yocto",
	r: "ronto",
	q: "quecto",
};
// Unit catalog. Each factor converts one displayed unit into this app's base
// unit system: meter for length, second for time, gram for mass, and SI-style
// base dimensions for the other quantities. Compound dimensions are stored as
// exponent maps, for example newton = g*m/s^2.
export const NAMED_UNITS = {
	s: {
		name: "second",
		dim: { Time: 1 },
		factor: 1,
		allowPrefix: true,
		category: "time",
		aliases: ["sec"],
	},
	m: {
		name: "meter",
		dim: { Length: 1 },
		factor: 1,
		allowPrefix: true,
		category: "geometry",
		aliases: ["meter"],
	},
	g: {
		name: "gram",
		dim: { Mass: 1 },
		factor: 1,
		allowPrefix: true,
		category: "mass",
	},
	A: {
		name: "ampere",
		dim: { ElectricCurrent: 1 },
		factor: 1,
		allowPrefix: true,
		category: "electrical",
		aliases: ["amp"],
	},
	K: {
		name: "kelvin",
		dim: { Temperature: 1 },
		factor: 1,
		allowPrefix: true,
		category: "temperature",
		aliases: ["kelvin", "degK"],
	},
	mol: {
		name: "mole",
		dim: { AmountOfSubstance: 1 },
		factor: 1,
		allowPrefix: true,
		category: "chemistry",
	},
	day: {
		name: "day",
		plural: "days",
		dim: { Time: 1 },
		factor: 86400,
		allowPrefix: false,
		category: "time",
		aliases: ["day"],
	},
	cd: {
		name: "candela",
		dim: { LuminousIntensity: 1 },
		factor: 1,
		allowPrefix: true,
		category: "photometry",
	},

	Hz: {
		name: "hertz",
		dim: { Time: -1 },
		factor: 1,
		allowPrefix: true,
		category: "time",
		invariantPlural: true,
	},
	deg: {
		name: "degree",
		plural: "degrees",
		dim: { PlaneAngle: 1 },
		factor: Math.PI / 180,
		allowPrefix: false,
		category: "geometry",
		hint: "Type deg (no ° symbol).",
	},
	arcmin: {
		name: "arcminute",
		dim: { PlaneAngle: 1 },
		factor: Math.PI / 10800,
		allowPrefix: false,
		category: "geometry",
		aliases: ["arcminute"],
		hint: "Type arcmin (no ′ character).",
	},
	arcsec: {
		name: "arcsecond",
		dim: { PlaneAngle: 1 },
		factor: Math.PI / 648000,
		allowPrefix: false,
		category: "geometry",
		aliases: ["arcsecond"],
		hint: "Type arcsec (no ″ character).",
	},
	rad: {
		name: "radian",
		dim: { PlaneAngle: 1 },
		factor: 1,
		allowPrefix: false,
		category: "geometry",
	},
	sr: {
		name: "steradian",
		dim: { SolidAngle: 1 },
		factor: 1,
		allowPrefix: false,
		category: "geometry",
	},
	N: {
		name: "newton",
		dim: { Mass: 1, Length: 1, Time: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "mechanical",
	},
	Pa: {
		name: "pascal",
		dim: { Mass: 1, Length: -1, Time: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "mechanical",
	},
	J: {
		name: "joule",
		dim: { Mass: 1, Length: 2, Time: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "mechanical",
	},
	W: {
		name: "watt",
		dim: { Mass: 1, Length: 2, Time: -3 },
		factor: 1e3,
		allowPrefix: true,
		category: "mechanical",
	},
	C: {
		name: "coulomb",
		dim: { ElectricCurrent: 1, Time: 1 },
		factor: 1,
		allowPrefix: true,
		category: "electrical",
		aliases: ["coul"],
	},
	V: {
		name: "volt",
		dim: { Mass: 1, Length: 2, Time: -3, ElectricCurrent: -1 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	Wb: {
		name: "weber",
		dim: { Mass: 1, Length: 2, Time: -2, ElectricCurrent: -1 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	T: {
		name: "tesla",
		dim: { Mass: 1, Time: -2, ElectricCurrent: -1 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	F: {
		name: "farad",
		dim: { Mass: -1, Length: -2, Time: 4, ElectricCurrent: 2 },
		factor: 1 / 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	ohm: {
		name: "ohm",
		dim: { Mass: 1, Length: 2, Time: -3, ElectricCurrent: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	S: {
		name: "siemens",
		dim: { Mass: -1, Length: -2, Time: 3, ElectricCurrent: 2 },
		factor: 1 / 1e3,
		allowPrefix: true,
		category: "electrical",
		invariantPlural: true,
	},
	H: {
		name: "henry",
		dim: { Mass: 1, Length: 2, Time: -2, ElectricCurrent: -2 },
		factor: 1e3,
		allowPrefix: true,
		category: "electrical",
	},
	degC: {
		name: "degree Celsius",
		plural: "degrees Celsius",
		dim: { Temperature: 1 },
		factor: 1,
		// Offset is applied before/after scaling in convertValue. Offset units are
		// intentionally restricted from compound expressions by the parser.
		offset: 273.15,
		allowPrefix: false,
		category: "temperature",
		hint: "Type degC (no ° symbol).",
	},
	lm: {
		name: "lumen",
		dim: { LuminousIntensity: 1, SolidAngle: 1 },
		factor: 1,
		allowPrefix: true,
		category: "photometry",
	},
	lx: {
		name: "lux",
		dim: { LuminousIntensity: 1, Length: -2 },
		factor: 1,
		allowPrefix: true,
		category: "photometry",
		invariantPlural: true,
	},
	Bq: {
		name: "becquerel",
		dim: { Time: -1 },
		factor: 1,
		allowPrefix: true,
		category: "radioactivity",
	},
	Gy: {
		name: "gray",
		plural: "grays",
		dim: { Length: 2, Time: -2 },
		factor: 1,
		allowPrefix: true,
		category: "radiation",
	},
	Sv: {
		name: "sievert",
		dim: { Length: 2, Time: -2 },
		factor: 1,
		allowPrefix: true,
		category: "radiation",
	},
	kat: {
		name: "katal",
		dim: { AmountOfSubstance: 1, Time: -1 },
		factor: 1,
		allowPrefix: true,
		category: "chemistry",
	},

	h: {
		name: "hour",
		dim: { Time: 1 },
		factor: 3600,
		allowPrefix: false,
		category: "time",
		aliases: ["hr"],
	},
	min: {
		name: "minute",
		dim: { Time: 1 },
		factor: 60,
		allowPrefix: false,
		category: "time",
	},
	L: {
		name: "litre",
		dim: { Length: 3 },
		factor: 1e-3,
		allowPrefix: true,
		category: "geometry",
		aliases: ["l", "liter", "litre"],
	},
	ha: {
		name: "hectare",
		dim: { Length: 2 },
		factor: 1e4,
		allowPrefix: false,
		category: "geometry",
		aliases: ["hectare"],
	},
	t: {
		name: "tonne",
		dim: { Mass: 1 },
		factor: 1e6,
		allowPrefix: false,
		aliases: ["tonne", "ton"],
		category: "mass",
	},
	eV: {
		name: "electronvolt",
		dim: { Mass: 1, Length: 2, Time: -2 },
		factor: 1.602176634e-19 * 1e3,
		allowPrefix: true,
		category: "mechanical",
		aliases: ["electronvolt", "ev"],
	},
	Da: {
		name: "dalton",
		dim: { Mass: 1 },
		factor: 1.6605390666e-24,
		allowPrefix: true,
		category: "mass",
		aliases: ["u", "amu", "dalton"],
	},
	bar: {
		name: "bar",
		dim: { Mass: 1, Length: -1, Time: -2 },
		factor: 1e5 * 1e3,
		allowPrefix: false,
		category: "mechanical",
		aliases: ["b"],
	},
	atm: {
		name: "standard atmosphere",
		dim: { Mass: 1, Length: -1, Time: -2 },
		factor: 101325 * 1e3,
		allowPrefix: false,
		category: "mechanical",
		aliases: ["atmosphere"],
	},
	Torr: {
		name: "torr",
		dim: { Mass: 1, Length: -1, Time: -2 },
		factor: (101325 / 760) * 1e3,
		allowPrefix: false,
		category: "mechanical",
		aliases: ["torr", "mmHg"],
	},
	B: {
		name: "bel",
		dim: { LogLevelBel: 1 },
		factor: 1,
		allowPrefix: true,
		category: "logarithmicBel",
		aliases: ["bel"],
		hint: "Use B for bel; decibel is dB.",
	},
	Np: {
		name: "neper",
		dim: { LogLevelNeper: 1 },
		factor: 1,
		allowPrefix: false,
		category: "logarithmicNeper",
		aliases: ["neper"],
	},
	// smoot: {
	// 	name: "smoot",
	// 	dim: { Length: 1 },
	// 	factor: 1.7018, // m per smoot (≈ 1.7018 m)
	// 	allowPrefix: false,
	// 	aliases: ["smoot", "sm"],
	// 	category: "nonsense",
	// 	hint: "Oliver Smoot’s height. Conversion: 1 smoot ≈ 1.7018 m = 170.18 cm.",
	// },

	// potrzebie: {
	// 	name: "potrzebie",
	// 	dim: { Length: 1 },
	// 	factor: 0.022636, // m per potrzebie (≈ 2.2636 cm)
	// 	allowPrefix: false,
	// 	aliases: ["potrzebie", "ptb"],
	// 	category: "nonsense",
	// 	hint: "MAD Magazine joke unit (thickness of MAD issue #26). Conversion (commonly cited): 1 potrzebie ≈ 2.2636 cm = 0.022636 m.",
	// },

	// jiffy: {
	// 	name: "jiffy",
	// 	dim: { Time: 1 },
	// 	factor: 1, // s per jiffy (1 jiffy = 1 s)
	// 	allowPrefix: false,
	// 	aliases: ["jiffy"],
	// 	category: "nonsense",
	// 	hint: "Colloquial ‘a short time’ (varies by context). In this library it’s defined as: 1 jiffy = 1 s = 1000 ms.",
	// },

	// furlongPerFortnight: {
	// 	name: "furlong per fortnight",
	// 	dim: { Length: 1, Time: -1 },
	// 	factor: 201.168 / 1209600, // m/s per (furlong/fortnight)
	// 	allowPrefix: false,
	// 	aliases: ["furlongfortnight", "fpf"],
	// 	category: "nonsense",
	// 	hint: "Speed unit. 1 furlong = 201.168 m; 1 fortnight = 14 days = 1,209,600 s. So 1 fpf = 201.168/1,209,600 m/s ≈ 1.6631×10⁻⁴ m/s (≈ 0.00016631 m/s).",
	// },

	// beardSecond: {
	// 	name: "beard-second",
	// 	dim: { Length: 1 },
	// 	factor: 1e-9, // m per beard-second (1 beard-second = 1 nm)
	// 	allowPrefix: false,
	// 	aliases: ["beardsecond"],
	// 	category: "nonsense",
	// 	hint: "‘Distance a beard grows in one second’ (highly variable). Here it’s fixed as: 1 beard-second = 1 nm = 1×10⁻⁹ m = 1×10⁻⁷ cm.",
	// },

	// helen: {
	// 	name: "helen",
	// 	dim: { Dimensionless: 1 },
	// 	factor: 1,
	// 	allowPrefix: true,
	// 	aliases: ["helen"],
	// 	category: "nonsense",
	// 	hint: "Beauty gag unit: 1 helen ‘launches’ 1000 ships. So 1 millihelen (mhelen) = 1 ship.",
	// },

	// sagan: {
	// 	name: "sagan",
	// 	dim: { Dimensionless: 1 },
	// 	factor: 1e9,
	// 	allowPrefix: true,
	// 	aliases: ["sagan"],
	// 	category: "nonsense",
	// 	hint: "Quantity gag unit meaning ‘billions and billions’. Here defined as: 1 sagan = 1×10⁹ (one billion).",
	// },

	// bananaEquivalentDose: {
	// 	name: "banana equivalent dose",
	// 	dim: { Mass: 1, Length: 2, Time: -2 }, // energy-like placeholder
	// 	factor: 1.0e-7 * 1e3, // placeholder in your base units
	// 	allowPrefix: false,
	// 	aliases: ["banana equivalent dose", "banana", "bed"],
	// 	category: "nonsense",
	// 	hint: "Humorous radiation comparison based on K-40 in a banana (not formal dosimetry). Common reference: 1 banana ≈ 0.1 μSv = 1×10⁻⁷ Sv (order-of-magnitude).",
	// },

	// mickey: {
	// 	name: "mickey",
	// 	plural: "mickeys",
	// 	dim: { Length: 1 },
	// 	factor: 1e-4, // m per mickey (0.01 cm = 0.1 mm = 1×10⁻⁴ m)
	// 	allowPrefix: false,
	// 	aliases: ["mickey"],
	// 	category: "nonsense",
	// 	hint: "Slang for a tiny mouse-movement increment (depends on hardware/software). Here defined as: 1 mickey = 0.01 cm = 0.1 mm = 1×10⁻⁴ m.",
	// },
};
// Aliases let user-facing names resolve to the canonical keys in NAMED_UNITS.
export const UNIT_ALIASES = Object.entries(NAMED_UNITS).flatMap(([key, def]) =>
	(def.aliases || []).map((alias) => [alias, key]),
);
// Longest-first sorting prevents partial symbol matches while tokenizing.
export const ALL_UNIT_SYMBOLS = [
	...Object.keys(NAMED_UNITS),
	...UNIT_ALIASES.map(([alias]) => alias),
].sort((a, b) => b.length - a.length);
export const BASE_UNITS = Object.keys(NAMED_UNITS).sort((a, b) => b.length - a.length);
export const PREFIXES = Object.keys(PREFIX_MULTIPLIERS);
